version: "3.6"

services:
  app:
    build: .
    container_name: app
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      JWT_KEY: ${JWT_KEY}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      BEARER_KEY: ${BEARER_KEY}
      DATABASE_URL: ${DATABASE_URL}
