version: "3.6"

services:
  app:
    build: .
    container_name: app
    ports:
      - "80:3000"
    environment:
      TOKEN_KEY: ${TOKEN_KEY}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      BASE_URL: ${BASE_URL}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      MIDTRANS_AUTH: ${MIDTRANS_AUTH}
